$env:MONITORING_API_URL = "https://IP_DEL_SERVIDOR/api/v1/metrics/ingest/"
$env:MONITORING_AGENT_TOKEN = "TOKEN_DEL_SERVIDOR"
$env:MONITORING_HOSTNAME = "WIN-SRV-01"
$env:MONITORING_SKIP_TLS_VERIFY = "false"
